### PR TITLE
php8 compat

### PR DESCRIPTION
**Pull request by asmundstavdahl**
Resolves issue #11

### CODE REVIEW

**Comment by zuiderkwast** [comment]
Thanks for the PR. According to https://www.dokuwiki.org/requirements DokuWiki supports PHP version 5.6 up to latest PHP version 7.4.x. I think we should support the same versions. Is `fn(...) => ...` valid in PHP 5.6? If not, is it possible to rewrite it in a way which works with both PHP 5.6 and the PHP 8?

**Comment by zuiderkwast** [comment]
I think `$in_ns` can be replaced by a regular `private function isIdInNamespace($id, $ns) { ... }`.

**Comment by asmundstavdahl** [comment]
Good idea. Now it should support old PHP versions as well.

**Comment by zuiderkwast** [comment]
Thanks Åsmund!

**Pull request merged**
